[package]
name = "arestoken"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.9.3"
solana-program-test = "1.9.3"
solana-sdk = { version = "1.9.3", features = ["full"] }
